"""pass delete

Revision ID: 43f620975e64
Revises: 649975b2edb3
Create Date: 2025-05-20 16:03:13.445684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43f620975e64'
down_revision: Union[str, None] = '649975b2edb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('utilisateurs', 'motDePasse', schema='auth_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utilisateurs', sa.Column('motDePasse', sa.VARCHAR(), autoincrement=False, nullable=False), schema='auth_schema')

    # ### end Alembic commands ###
