"""create utilisateur table

Revision ID: 649975b2edb3
Revises: 
Create Date: 2025-05-06 17:24:37.841618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '649975b2edb3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('motDePasse', sa.String(), nullable=False),
    sa.Column('fonction', sa.Enum('DOCTORANT', 'POST_DOCTORANT', 'ASSISTANT_PROFESSEUR', 'PROFESSEUR', 'STAGIAIRE', 'PERSONNEL', name='fonctionenum'), nullable=False),
    sa.Column('statut', sa.Enum('ACTIVATED', 'INACTIVATED', 'ARCHIVED', name='userstatusenum'), nullable=True),
    sa.Column('role', sa.Enum('BPA', 'CG', 'RH', 'USER', name='roleenum'), nullable=False),
    sa.Column('unite', sa.Enum('FMS', 'SHCC', 'CHU', 'UM6P', name='uniteenum'), nullable=False),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('dateInscription', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='auth_schema'
    )
    op.create_index(op.f('ix_auth_schema_utilisateurs_email'), 'utilisateurs', ['email'], unique=True, schema='auth_schema')
    op.create_index(op.f('ix_auth_schema_utilisateurs_username'), 'utilisateurs', ['username'], unique=True, schema='auth_schema')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_schema_utilisateurs_username'), table_name='utilisateurs', schema='auth_schema')
    op.drop_index(op.f('ix_auth_schema_utilisateurs_email'), table_name='utilisateurs', schema='auth_schema')
    op.drop_table('utilisateurs', schema='auth_schema')
    # ### end Alembic commands ###
