"""enums deletion

Revision ID: f42b6b997a83
Revises: 43f620975e64
Create Date: 2025-05-20 16:20:46.773597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f42b6b997a83'
down_revision: Union[str, None] = '43f620975e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('utilisateurs', 'fonction',
               existing_type=postgresql.ENUM('DOCTORANT', 'POST_DOCTORANT', 'ASSISTANT_PROFESSEUR', 'PROFESSEUR', 'STAGIAIRE', 'PERSONNEL', name='fonctionenum'),
               type_=sa.String(),
               existing_nullable=False,
               schema='auth_schema')
    op.alter_column('utilisateurs', 'statut',
               existing_type=postgresql.ENUM('ACTIVATED', 'INACTIVATED', 'ARCHIVED', name='userstatusenum'),
               type_=sa.String(),
               existing_nullable=True,
               schema='auth_schema')
    op.alter_column('utilisateurs', 'role',
               existing_type=postgresql.ENUM('BPA', 'CG', 'RH', 'USER', name='roleenum'),
               type_=sa.String(),
               existing_nullable=False,
               schema='auth_schema')
    op.alter_column('utilisateurs', 'unite',
               existing_type=postgresql.ENUM('FMS', 'SHCC', 'CHU', 'UM6P', name='uniteenum'),
               type_=sa.String(),
               existing_nullable=False,
               schema='auth_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('utilisateurs', 'unite',
               existing_type=sa.String(),
               type_=postgresql.ENUM('FMS', 'SHCC', 'CHU', 'UM6P', name='uniteenum'),
               existing_nullable=False,
               schema='auth_schema')
    op.alter_column('utilisateurs', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('BPA', 'CG', 'RH', 'USER', name='roleenum'),
               existing_nullable=False,
               schema='auth_schema')
    op.alter_column('utilisateurs', 'statut',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ACTIVATED', 'INACTIVATED', 'ARCHIVED', name='userstatusenum'),
               existing_nullable=True,
               schema='auth_schema')
    op.alter_column('utilisateurs', 'fonction',
               existing_type=sa.String(),
               type_=postgresql.ENUM('DOCTORANT', 'POST_DOCTORANT', 'ASSISTANT_PROFESSEUR', 'PROFESSEUR', 'STAGIAIRE', 'PERSONNEL', name='fonctionenum'),
               existing_nullable=False,
               schema='auth_schema')

    # ### end Alembic commands ###
